server:
  port: 9002

spring:
  application:
    name: gateway-client

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoint:
    web:
      exposure:
        include: "*"