server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://43.140.193.197:3301/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.lihh.pojo